version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  celery_beat:
    build: .
    command: 'celery -A tasks.tasks.app beat -l INFO'
    depends_on:
      - db
      - redis
    volumes:
      - ./src/:/app
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CRAWLER_INTERVAL=30

  celery_worker:
    build: .
    # command: 'celery -A tasks.tasks.app worker -l INFO'
    command: tail -f /dev/null
    depends_on:
      - db
      - redis
    volumes:
      - ./src/:/app
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CRAWLER_INTERVAL=90
      - IMMUDB_API_TOKEN=

  web:
    build: .
    command: 'python app.py'
    volumes:
      - ./src/:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - IMMUDB_API_TOKEN=

  redis:
    image: redis:6-alpine
