version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
